#!/bin/bash
# SATNOGS_POST_OBSERVATION_SCRIPT="satnogs-post {{ID}} {{FREQ}} {{TLE}} {{TIMESTAMP}} {{BAUD}} {{SCRIPT_NAME}}"

grsat.py stop "$@"
satdump.sh stop "$@"
meteor.sh stop "$@"
iq_dump_rename.sh "$@"
bandscan.sh start
direwolf.sh start
rotor-park.sh
